import { Platform } from 'react-native';

const tokens = {
    space: {
        xs: 4,
        sm: 8,
        md: 16,
        lg: 24,
        xl: 32,
        xxl: 48,
    },
    radius: {
        sm: 8,
        md: 12,
        lg: 16,
        xl: 24,
        pill: 999,
    },
    fontSize: {
        xs: 12,
        sm: 14,
        md: 16,
        lg: 18,
        xl: 22,
        xxl: 28,
        hero: 36,
    },
    fontWeight: {
        regular: '400',
        medium: '500',
        semibold: '600',
        bold: '700',
    },
    shadow: {
        sm: {
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.04,
            shadowRadius: 6,
            elevation: 2,
        },
        md: {
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 6 },
            shadowOpacity: 0.06,
            shadowRadius: 14,
            elevation: 5,
        },
        lg: {
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 10 },
            shadowOpacity: 0.08,
            shadowRadius: 24,
            elevation: 10,
        },
    },
};

const colors = {
    brand:      '#009ee0',
    brandDark:  '#007ab8',
    brandLight: '#33b5e8',
    gray50:  '#F8F9FA',
    gray100: '#F1F3F5',
    gray200: '#E9ECEF',
    gray300: '#DEE2E6',
    gray400: '#CED4DA',
    gray500: '#ADB5BD',
    gray600: '#6C757D',
    gray700: '#495057',
    gray800: '#343A40',
    gray900: '#212529',
    gray:        '#454545',
    lightblue:   '#40C4FF',
    blue:        '#006F9F',
    darkblue:    '#0D47A1',
    darkred:     '#D50000',
    backgroundGrey: '#E9E9EF',
};

const hintColors = {
    green: '#55da59',
    gray: '#9499a1AA',
};

const colors200 = {
    red:        '#EF9A9A',
    pink:       '#F48FB1',
    purple:     '#CE93D8',
    deepPurple: '#B39DDB',
    indigo:     '#9FA8DA',
    blue:       '#90CAF9',
    lightBlue:  '#81D4FA',
    cyan:       '#80DEEA',
    teal:       '#80CBC4',
    green:      '#A5D6A7',
    lightGreen: '#C5E1A5',
    lime:       '#E6EE9C',
    yellow:     '#FFF59D',
    amber:      '#FFE082',
    orange:     '#FFCC80',
    deepOrange: '#FFAB91',
    brown:      '#BCAAA4',
    grey:       '#EEEEEE',
    blueGrey:   '#B0BEC5',
};

const colors50 = {
    red:        '#FFEBEE',
    pink:       '#FCE4EC',
    purple:     '#F3E5F5',
    deepPurple: '#EDE7F6',
    indigo:     '#E8EAF6',
    blue:       '#E3F2FD',
    lightBlue:  '#E1F5FE',
    cyan:       '#E0F7FA',
    teal:       '#E0F2F1',
    green:      '#E8F5E9',
    lightGreen: '#F1F8E9',
    lime:       '#F9FBE7',
    yellow:     '#FFFDE7',
    amber:      '#FFF8E1',
    orange:     '#FFF3E0',
    deepOrange: '#FBE9E7',
    brown:      '#EFEBE9',
    grey:       '#FAFAFA',
    blueGrey:   '#ECEFF1',
};

const AppTheme = {
    primary:   '#007AFF',
    secondary: '#34C759',
};

const Theme = {
    light: {
        primary:       '#007AFF',
        primarySoft:   '#007AFF15',
        secondary:     '#5856D6',
        selection:     '#F2F2F7',
        accentFont:    '#FF3B30',
        font:          '#1C1C1E',
        fontSecondary: '#8E8E93',
        lightFont:     '#FFFFFF',
        link:          '#007AFF',
        icon:          '#1C1C1E',
        border:        '#E5E5EA',
        background:            '#F2F2F7',
        cardBackground:        '#FFFFFF',
        greyBackground:        '#E5E5EA',
        collapsableBackground: '#00000008',
        field:                 '#F2F2F7',
        fieldBorder:           '#E5E5EA',
        courseBackground: '#F2F2F7',
        eventBackground:  '#FFFFFF',
        eventBorder:      '#E5E5EA',
        sections:       ['#007AFF10', '#34C75910', '#FF950010', '#FF3B3010', '#5856D610', '#5AC8FA10'],
        sectionsHeaders: ['#007AFF', '#34C759', '#FF9500', '#FF3B30', '#5856D6', '#5AC8FA'],
        calendar: {
            selection: '#007AFF',
            currentDay: '#007AFF15',
            sunday: '#FF3B3010'
        },
        settings: {
            switchTrack: {
                false: '#E5E5EA',
                true:  '#007AFF',
            },
            background: {
                flex: 1,
                backgroundColor: '#F2F2F7',
            },
            separationText: {
                color:      '#8E8E93',
                fontSize:   tokens.fontSize.sm,
                fontWeight: tokens.fontWeight.semibold,
                marginTop:  tokens.space.lg,
                marginLeft: tokens.space.md,
                letterSpacing: 0.8,
                textTransform: 'uppercase',
            },
            button: {
                backgroundColor: '#FFFFFF',
                borderRadius:    tokens.radius.lg,
                marginHorizontal: tokens.space.md,
                marginTop:       tokens.space.sm,
                paddingVertical: tokens.space.md,
                flexDirection:   'row',
                alignContent:    'center',
                ...tokens.shadow.sm,
            },
            buttonMainText: {
                fontWeight:      tokens.fontWeight.medium,
                color:           '#1C1C1E',
                fontSize:        tokens.fontSize.md,
                marginHorizontal: tokens.space.md,
                alignSelf:       'center',
            },
            buttonSecondaryText: {
                fontWeight: tokens.fontWeight.regular,
                color:      '#8E8E93',
                fontSize:   tokens.fontSize.md,
                marginLeft: 'auto',
                alignSelf:  'center',
            },
            leftIcon: {
                marginLeft: tokens.space.md,
                color:      '#007AFF',
                alignSelf:  'center',
            },
            rightIcon: {
                alignSelf:       'center',
                color:           '#C7C7CC',
                marginHorizontal: tokens.space.xs,
            },
            popup: {
                filters: {
                    container: {
                        flex: 1,
                        flexGrow: 1,
                        backgroundColor: '#FFFFFF',
                        padding: tokens.space.md,
                        justifyContent: 'space-between',
                    },
                    header: {
                        flexDirection:  'row',
                        justifyContent: 'space-between',
                        alignItems:     'center',
                        marginTop:      tokens.space.sm,
                    },
                    button: {
                        backgroundColor: '#007AFF15',
                        padding:         tokens.space.sm,
                        borderRadius:    tokens.radius.lg,
                        margin:          tokens.space.sm,
                        flexDirection:   'row',
                        alignItems:      'center',
                    },
                    buttonText: {
                        fontSize:   tokens.fontSize.lg,
                        fontWeight: tokens.fontWeight.bold,
                        color:      '#007AFF',
                    },
                    iconColor: '#007AFF',
                    footer: {
                        marginTop:      tokens.space.md,
                        justifyContent: 'flex-end',
                        flexDirection:  'row',
                    },
                },
                background: {
                    flex:            1,
                    justifyContent:  'center',
                    backgroundColor: '#00000066',
                },
                container: {
                    backgroundColor: '#FFFFFF',
                    borderRadius:    tokens.radius.xl,
                    padding:         tokens.space.md,
                    marginHorizontal: tokens.space.md,
                    marginVertical:  tokens.space.xl,
                    ...tokens.shadow.lg,
                    flexShrink: 1,
                    maxHeight: '85%',
                },
                header: {
                    flexDirection:  'row',
                    justifyContent: 'space-between',
                    alignItems:     'center',
                },
                textHeader: {
                    fontWeight: tokens.fontWeight.bold,
                    fontSize:   tokens.fontSize.lg,
                    color:      '#1C1C1E',
                },
                textDescription: {
                    marginVertical: tokens.space.sm,
                    fontSize:       tokens.fontSize.md,
                    color:          '#8E8E93',
                },
                buttonContainer: {
                    flexDirection:  'row',
                    justifyContent: 'space-around',
                    marginTop:      tokens.space.xl,
                },
                buttonSecondary: {
                    flex:            1,
                    backgroundColor: '#F2F2F7',
                    borderRadius:    tokens.radius.md,
                    paddingVertical: tokens.space.sm,
                    marginHorizontal: tokens.space.xs,
                    alignItems:      'center',
                },
                buttonMain: {
                    flex:            1,
                    backgroundColor: '#007AFF',
                    borderRadius:    tokens.radius.md,
                    paddingVertical: tokens.space.sm,
                    marginHorizontal: tokens.space.xs,
                    alignItems:      'center',
                },
                buttonTextSecondary: {
                    fontSize: tokens.fontSize.lg,
                    color:    '#8E8E93',
                },
                buttonTextMain: {
                    fontSize: tokens.fontSize.lg,
                    color:    '#FFFFFF',
                },
                closeIcon: {
                    color: '#C7C7CC',
                },
                radioContainer: {
                    flexDirection:  'row',
                    alignContent:   'center',
                    marginTop:      tokens.space.md,
                },
                radioIconColor: '#007AFF',
                radioText: {
                    fontSize:  tokens.fontSize.lg,
                    marginLeft: tokens.space.md,
                    color:     '#1C1C1E',
                },
                filterListContainer: {
                    flex:           1,
                    flexDirection:  'row',
                    justifyContent: 'space-around',
                },
                textInputContainer: {
                    flexDirection:   'row',
                    alignItems:      'center',
                    marginHorizontal: tokens.space.xs,
                    marginTop:       tokens.space.md,
                    justifyContent:  'flex-end',
                },
                textInput: {
                    borderWidth:  1.5,
                    borderColor:  '#E5E5EA',
                    borderRadius: tokens.radius.md,
                    padding:      tokens.space.sm,
                    paddingVertical: Platform.OS === 'ios' ? tokens.space.sm : tokens.space.xs,
                    flex:         1,
                    marginRight:  tokens.space.xs,
                    color:        '#1C1C1E',
                    backgroundColor: '#F8F9FA',
                },
                textInputIconColor:        '#007AFF',
                textInputPlaceholderColor: '#C7C7CC',
            },
        },
        courses: {
            '#FFFF00': '#FFCC00',
            '#00FFFF': '#5AC8FA',
            '#800040': '#5856D6',
            '#808000': '#A2845E',
            '#800000': '#FF3B30',
            '#8000FF': '#FF9500',
            '#00FF00': '#34C759',
            '#400080': '#007AFF',
            default:   '#007AFF',
        },
    },
    dark: {
        primary:       '#5E5CE6',
        primarySoft:   '#0A84FF20',
        accent:        '#5E5CE6',
        secondary:     '#30D158',
        selection:     '#2C2C2E',
        accentFont:    '#FF453A',
        font:          '#FFFFFF',
        fontSecondary: '#8E8E93',
        lightFont:     '#FFFFFF',
        link:          '#64D2FF',
        icon:          '#FFFFFF',
        border:        '#38383A',
        background:            '#000000',
        cardBackground:        '#1C1C1E',
        greyBackground:        '#121212',
        collapsableBackground: '#FFFFFF0A',
        field:                 '#2C2C2E',
        fieldBorder:           '#38383A',
        courseBackground: '#000000',
        eventBackground:  '#1C1C1E',
        eventBorder:      '#2C2C2E',
        sections:        ['#0A84FF15', '#30D15815', '#FF9F0A15', '#FF453A15', '#5E5CE615', '#64D2FF15'],
        sectionsHeaders: ['#5E5CE6', '#30D158', '#FF9F0A', '#FF453A', '#5E5CE6', '#64D2FF'],
        calendar: {
            selection: '#5E5CE6',
            currentDay: '#1C1C1E',
            sunday: '#FF453A15',
        },
        settings: {
            switchTrack: {
                false: '#38383A',
                true:  '#5E5CE6',
            },
            background: {
                flex: 1,
                backgroundColor: '#000000',
            },
            separationText: {
                color:      '#8E8E93',
                fontSize:   tokens.fontSize.sm,
                fontWeight: tokens.fontWeight.semibold,
                marginTop:  tokens.space.lg,
                marginLeft: tokens.space.md,
                letterSpacing: 0.8,
                textTransform: 'uppercase',
            },
            button: {
                backgroundColor: '#1C1C1E',
                borderRadius:    tokens.radius.lg,
                marginHorizontal: tokens.space.md,
                marginTop:       tokens.space.sm,
                paddingVertical: tokens.space.md,
                flexDirection:   'row',
                alignContent:    'center',
                ...tokens.shadow.sm,
            },
            buttonMainText: {
                fontWeight:      tokens.fontWeight.medium,
                color:           '#FFFFFF',
                fontSize:        tokens.fontSize.md,
                marginHorizontal: tokens.space.md,
                alignSelf:       'center',
            },
            buttonSecondaryText: {
                fontWeight: tokens.fontWeight.regular,
                color:      '#8E8E93',
                fontSize:   tokens.fontSize.md,
                marginLeft: 'auto',
                alignSelf:  'center',
            },
            leftIcon: {
                marginLeft: tokens.space.md,
                color:      '#5E5CE6',
                alignSelf:  'center',
            },
            rightIcon: {
                alignSelf:        'center',
                color:            '#8E8E93',
                marginHorizontal: tokens.space.xs,
            },
            popup: {
                filters: {
                    container: {
                        flex:            1,
                        flexGrow:        1,
                        backgroundColor: '#1C1C1E',
                        padding:         tokens.space.md,
                        justifyContent:  'space-between',
                    },
                    header: {
                        flexDirection:  'row',
                        justifyContent: 'space-between',
                        alignItems:     'center',
                        marginTop:      tokens.space.sm,
                    },
                    button: {
                        backgroundColor: '#2C2C2E',
                        padding:         tokens.space.sm,
                        borderRadius:    tokens.radius.lg,
                        margin:          tokens.space.sm,
                        flexDirection:   'row',
                        alignItems:      'center',
                    },
                    buttonText: {
                        fontSize:   tokens.fontSize.lg,
                        fontWeight: tokens.fontWeight.bold,
                        color:      '#5E5CE6',
                    },
                    iconColor: '#5E5CE6',
                    footer: {
                        marginTop:      tokens.space.md,
                        justifyContent: 'flex-end',
                        flexDirection:  'row',
                    },
                },
                background: {
                    flex:            1,
                    justifyContent:  'center',
                    backgroundColor: '#00000080',
                },
                container: {
                    backgroundColor: '#1C1C1E',
                    borderRadius:    tokens.radius.xl,
                    padding:         tokens.space.md,
                    marginHorizontal: tokens.space.md,
                    marginVertical:  tokens.space.xl,
                    ...tokens.shadow.lg,
                    flexShrink: 1,
                    maxHeight: '85%',
                },
                header: {
                    flexDirection:  'row',
                    justifyContent: 'space-between',
                    alignItems:     'center',
                },
                textHeader: {
                    fontWeight: tokens.fontWeight.bold,
                    fontSize:   tokens.fontSize.lg,
                    color:      '#FFFFFF',
                },
                textDescription: {
                    marginVertical: tokens.space.sm,
                    fontSize:       tokens.fontSize.md,
                    color:          '#8E8E93',
                },
                buttonContainer: {
                    flexDirection:  'row',
                    justifyContent: 'space-around',
                    marginTop:      tokens.space.xl,
                },
                buttonSecondary: {
                    flex:            1,
                    backgroundColor: '#2C2C2E',
                    borderRadius:    tokens.radius.md,
                    paddingVertical: tokens.space.sm,
                    marginHorizontal: tokens.space.xs,
                    alignItems:      'center',
                },
                buttonMain: {
                    flex:            1,
                    backgroundColor: '#5E5CE6',
                    borderRadius:    tokens.radius.md,
                    paddingVertical: tokens.space.sm,
                    marginHorizontal: tokens.space.xs,
                    alignItems:      'center',
                },
                buttonTextSecondary: {
                    fontSize: tokens.fontSize.lg,
                    color:    '#8E8E93',
                },
                buttonTextMain: {
                    fontSize: tokens.fontSize.lg,
                    color:    '#FFFFFF',
                },
                closeIcon: {
                    color: '#8E8E93',
                },
                radioContainer: {
                    flexDirection: 'row',
                    alignContent:  'center',
                    marginTop:     tokens.space.md,
                },
                radioIconColor: '#5E5CE6',
                radioText: {
                    fontSize:   tokens.fontSize.lg,
                    marginLeft: tokens.space.md,
                    color:      '#FFFFFF',
                },
                filterListContainer: {
                    flex:           1,
                    flexDirection:  'row',
                    justifyContent: 'space-around',
                },
                textInputContainer: {
                    flexDirection:    'row',
                    alignItems:       'center',
                    marginHorizontal: tokens.space.xs,
                    marginTop:        tokens.space.md,
                    justifyContent:   'flex-end',
                },
                textInput: {
                    borderWidth:  1.5,
                    borderColor:  '#38383A',
                    borderRadius: tokens.radius.md,
                    padding:      tokens.space.sm,
                    paddingVertical: Platform.OS === 'ios' ? tokens.space.sm : tokens.space.xs,
                    flex:         1,
                    marginRight:  tokens.space.xs,
                    color:        '#FFFFFF',
                    backgroundColor: '#2C2C2E',
                },
                textInputIconColor:        '#5E5CE6',
                textInputPlaceholderColor: '#8E8E93',
            },
        },
        courses: {
            '#FFFF00': '#FFD60A',
            '#00FFFF': '#64D2FF',
            '#800040': '#BF5AF2',
            '#808000': '#8E8E93',
            '#800000': '#FF453A',
            '#8000FF': '#FF9F0A',
            '#00FF00': '#30D158',
            '#400080': '#5E5CE6',
            default:   '#5E5CE6',
        },
    },
};

const StyleWelcome = {
    light: {
        buttonContainer: {
            backgroundColor: '#FFFFFF',
            borderRadius: tokens.radius.pill,
            paddingVertical: tokens.space.md,
            marginHorizontal: tokens.space.xl,
            marginVertical: tokens.space.md,
            ...tokens.shadow.md,
            justifyContent: 'center',
        },
        buttonText: {
            fontFamily: 'Montserrat_600SemiBold',
            fontSize: tokens.fontSize.md,
            color: '#5E5CE6',
            alignSelf: 'center',
            letterSpacing: 0.5,
        },
        mainText: {
            fontFamily: 'Montserrat_700Bold',
            fontSize: tokens.fontSize.hero,
            alignSelf: 'center',
            color: '#FFFFFF',
            marginTop: tokens.space.xxl,
            letterSpacing: -0.5,
            textAlign: 'center',
        },
        secondaryText: {
            fontFamily: 'Montserrat_500Medium',
            fontSize: tokens.fontSize.lg,
            alignSelf: 'center',
            color: '#FFFFFFCC',
            marginHorizontal: tokens.space.xl,
            textAlign: 'center',
            marginTop: tokens.space.lg,
            lineHeight: 28,
        },
        pageDots: {
            flexDirection: 'row',
            justifyContent: 'center',
            alignItems: 'center',
            marginVertical: tokens.space.md,
        },
        circleFill: {
            width: 24,
            height: 8,
            marginHorizontal: tokens.space.xs,
            borderRadius: tokens.radius.pill,
            backgroundColor: '#FFFFFF',
        },
        circleEmpty: {
            width: 8,
            height: 8,
            borderRadius: tokens.radius.pill,
            marginHorizontal: tokens.space.xs,
            backgroundColor: '#FFFFFF44',
        },
        whiteCardContainer: {
            flexShrink: 1,
        },
        whiteCard: {
            backgroundColor: '#FFFFFFEE',
            borderRadius: tokens.radius.xl,
            padding: tokens.space.lg,
            marginHorizontal: tokens.space.md,
            marginVertical: tokens.space.md,
            ...tokens.shadow.lg,
        },
        whiteCardText: {
            fontFamily: 'Montserrat_600SemiBold',
            fontSize: tokens.fontSize.lg,
            marginBottom: tokens.space.md,
            color: '#1A1D23',
            letterSpacing: 0.1,
        },
        whiteCardButton: {
            backgroundColor: '#F5F7FA',
            borderRadius: tokens.radius.md,
            borderColor: '#E0E4EA',
            borderWidth: 1.5,
            paddingVertical: tokens.space.sm,
            paddingHorizontal: tokens.space.md,
            marginRight: tokens.space.sm,
            marginBottom: tokens.space.sm,
        },
        whiteCardButtonSelected: {
            backgroundColor: '#5E5CE6',
            borderRadius: tokens.radius.md,
            borderColor: '#5E5CE6',
            borderWidth: 1.5,
            paddingVertical: tokens.space.sm,
            paddingHorizontal: tokens.space.md,
            marginRight: tokens.space.sm,
            marginBottom: tokens.space.sm,
        },
        whiteCardButtonText: {
            fontFamily: 'Montserrat_500Medium',
            fontSize: tokens.fontSize.sm,
            alignSelf: 'center',
            color: '#495057',
        },
        whiteCardButtonTextSelected: {
            fontFamily: 'Montserrat_500Medium',
            fontSize: tokens.fontSize.sm,
            alignSelf: 'center',
            color: '#FFFFFF',
        },
        whiteCardGroupButton: {
            backgroundColor: '#F5F7FA',
            borderRadius: tokens.radius.md,
            borderColor: '#E0E4EA',
            borderWidth: 1.5,
            paddingVertical: tokens.space.sm,
            paddingHorizontal: tokens.space.md,
            marginRight: tokens.space.sm,
            marginBottom: tokens.space.sm,
            flex: 1,
        },
        whiteCardGroupText: {
            fontFamily: 'Montserrat_500Medium',
            fontSize: tokens.fontSize.sm,
            color: '#495057',
        },
        greyBottomText: {
            fontFamily: 'Montserrat_500Medium',
            fontSize: tokens.fontSize.xs,
            marginTop: tokens.space.sm,
            marginHorizontal: tokens.space.sm,
            color: '#00000066',
            lineHeight: 18,
        },
        gradientColor: ['#5E5CE6', '#33b5e8', '#45D7E8'],
        placeholderTextColor: '#00000066',
        welcomeButtonIconColor: '#5E5CE6',
    },
    dark: {
        buttonContainer: {
            backgroundColor: '#3D2540',
            borderRadius: tokens.radius.pill,
            paddingVertical: tokens.space.md,
            marginHorizontal: tokens.space.xl,
            marginVertical: tokens.space.md,
            ...tokens.shadow.md,
            justifyContent: 'center',
        },
        buttonText: {
            fontFamily: 'Montserrat_600SemiBold',
            fontSize: tokens.fontSize.md,
            color: '#FFFFFF',
            alignSelf: 'center',
            letterSpacing: 0.5,
        },
        mainText: {
            fontFamily: 'Montserrat_700Bold',
            fontSize: tokens.fontSize.hero,
            alignSelf: 'center',
            color: '#FFFFFF',
            marginTop: tokens.space.xxl,
            letterSpacing: -0.5,
            textAlign: 'center',
        },
        secondaryText: {
            fontFamily: 'Montserrat_500Medium',
            fontSize: tokens.fontSize.lg,
            alignSelf: 'center',
            color: '#FFFFFFBB',
            marginHorizontal: tokens.space.xl,
            textAlign: 'center',
            marginTop: tokens.space.lg,
            lineHeight: 28,
        },
        pageDots: {
            flexDirection: 'row',
            justifyContent: 'center',
            alignItems: 'center',
            marginVertical: tokens.space.md,
        },
        circleFill: {
            width: 24,
            height: 8,
            marginHorizontal: tokens.space.xs,
            borderRadius: tokens.radius.pill,
            backgroundColor: '#FFFFFF',
        },
        circleEmpty: {
            width: 8,
            height: 8,
            borderRadius: tokens.radius.pill,
            marginHorizontal: tokens.space.xs,
            backgroundColor: '#FFFFFF33',
        },
        whiteCardContainer: {
            flexShrink: 1,
        },
        whiteCard: {
            backgroundColor: '#3D2540DD',
            borderRadius: tokens.radius.xl,
            padding: tokens.space.lg,
            marginHorizontal: tokens.space.md,
            marginVertical: tokens.space.md,
            ...tokens.shadow.lg,
        },
        whiteCardText: {
            fontFamily: 'Montserrat_600SemiBold',
            fontSize: tokens.fontSize.lg,
            marginBottom: tokens.space.md,
            color: '#F0EAF1',
            letterSpacing: 0.1,
        },
        whiteCardButton: {
            backgroundColor: '#2D1A2E',
            borderRadius: tokens.radius.md,
            borderColor: '#5A3A5C',
            borderWidth: 1.5,
            paddingVertical: tokens.space.sm,
            paddingHorizontal: tokens.space.md,
            marginRight: tokens.space.sm,
            marginBottom: tokens.space.sm,
        },
        whiteCardButtonSelected: {
            backgroundColor: '#FFFFFF',
            borderRadius: tokens.radius.md,
            borderColor: '#FFFFFF',
            borderWidth: 1.5,
            paddingVertical: tokens.space.sm,
            paddingHorizontal: tokens.space.md,
            marginRight: tokens.space.sm,
            marginBottom: tokens.space.sm,
        },
        whiteCardButtonText: {
            fontFamily: 'Montserrat_500Medium',
            fontSize: tokens.fontSize.sm,
            alignSelf: 'center',
            color: '#B1A5B2',
        },
        whiteCardButtonTextSelected: {
            fontFamily: 'Montserrat_500Medium',
            fontSize: tokens.fontSize.sm,
            alignSelf: 'center',
            color: '#2D1A2E',
        },
        whiteCardGroupButton: {
            backgroundColor: '#2D1A2E',
            borderRadius: tokens.radius.md,
            borderColor: '#5A3A5C',
            borderWidth: 1.5,
            paddingVertical: tokens.space.sm,
            paddingHorizontal: tokens.space.md,
            marginRight: tokens.space.sm,
            marginBottom: tokens.space.sm,
            flex: 1,
        },
        whiteCardGroupText: {
            fontFamily: 'Montserrat_500Medium',
            fontSize: tokens.fontSize.sm,
            color: '#B1A5B2',
        },
        greyBottomText: {
            fontFamily: 'Montserrat_500Medium',
            fontSize: tokens.fontSize.xs,
            marginTop: tokens.space.sm,
            marginHorizontal: tokens.space.sm,
            color: '#FFFFFF66',
            lineHeight: 18,
        },
        gradientColor: ['#120912', '#2D1A2E', '#713775'],
        placeholderTextColor: '#FFFFFF66',
        welcomeButtonIconColor: '#FFFFFF',
    },
};

const style = {
    tokens,
    colors,
    hintColors,

    schedule: {
        containerView: {
            flex: 1,
        },
        titleView: {
            paddingHorizontal: tokens.space.md,
            paddingVertical: tokens.space.sm,
        },
        titleText: {
            fontSize: tokens.fontSize.lg,
            fontWeight: tokens.fontWeight.bold,
        },
        contentView: {
            flex: 1,
        },
        course: {
            root: {
                flex: 1,
                flexDirection: 'column',
                marginVertical: tokens.space.sm,
                marginHorizontal: tokens.space.sm,
            },
            row: {
                flex: 1,
                flexDirection: 'row',
            },
            hours: {
                flexDirection: 'column',
                justifyContent: 'space-around',
                alignItems: 'center',
                paddingHorizontal: tokens.space.sm,
                paddingVertical: tokens.space.sm,
                minWidth: 64,
            },
            hoursText: {
                fontSize: tokens.fontSize.sm,
                fontWeight: tokens.fontWeight.bold,
                textAlign: 'center',
            },
            contentBlock: {
                flex: 1,
                flexDirection: 'column',
                paddingVertical: tokens.space.md,
                paddingRight: tokens.space.md,
            },
            contentType: {
                flex: 1,
                flexDirection: 'row',
                justifyContent: 'space-between',
                alignItems: 'flex-start',
                marginBottom: 4,
            },
            content: {
                fontSize: tokens.fontSize.sm,
            },
            title: {
                fontSize: tokens.fontSize.md,
                fontWeight: tokens.fontWeight.bold,
            },
            iconHeader: {
                flexDirection: 'row',
                alignItems: 'center',
                marginTop: tokens.space.xs,
            },
            line: {
                flexDirection: 'row',
                alignItems: 'center',
                marginTop: 6,
            },
            container: {
                flex: 1,
                marginLeft: tokens.space.xs,
            },
            groupsContainer: {
                flexDirection: 'row',
                flexWrap: 'wrap',
            },
            groupsContent: {
                flex: 1,
            },
            noCourse: {
                flex: 1,
                justifyContent: 'center',
                alignItems: 'center',
                paddingVertical: tokens.space.xxl,
            },
            noCourseText: {
                fontSize: tokens.fontSize.md,
                fontWeight: tokens.fontWeight.medium,
                opacity: 0.5,
            },
        },
    },

    offline: {
        container: {
            flex: 1,
            justifyContent: 'center',
            alignItems: 'center',
            padding: tokens.space.xl,
        },
        icon: {
            marginBottom: tokens.space.lg,
            opacity: 0.4,
        },
        title: {
            fontSize: tokens.fontSize.xl,
            fontWeight: tokens.fontWeight.bold,
            marginBottom: tokens.space.sm,
            textAlign: 'center',
        },
        subtitle: {
            fontSize: tokens.fontSize.md,
            textAlign: 'center',
            opacity: 0.6,
        },
    },

    course: {
        container: {
            flex: 1,
        },
        card: {
            borderRadius: tokens.radius.lg,
            marginHorizontal: tokens.space.md,
            marginVertical: tokens.space.sm,
            padding: tokens.space.md,
            ...tokens.shadow.md,
        },
        header: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            marginBottom: tokens.space.sm,
        },
        title: {
            fontSize: tokens.fontSize.lg,
            fontWeight: tokens.fontWeight.bold,
            flex: 1,
        },
        subtitle: {
            fontSize: tokens.fontSize.sm,
            marginTop: tokens.space.xs,
            opacity: 0.7,
        },
        badge: {
            borderRadius: tokens.radius.pill,
            paddingHorizontal: tokens.space.sm,
            paddingVertical: tokens.space.xs,
        },
        badgeText: {
            fontSize: tokens.fontSize.xs,
            fontWeight: tokens.fontWeight.semibold,
            color: '#FFFFFF',
        },
        infoRow: {
            flexDirection: 'row',
            alignItems: 'center',
            marginTop: tokens.space.sm,
        },
        infoText: {
            fontSize: tokens.fontSize.sm,
            marginLeft: tokens.space.sm,
        },
    },

    calendar: {
        container: {
            flex: 1,
        },
        header: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            paddingHorizontal: tokens.space.md,
            paddingVertical: tokens.space.sm,
        },
        headerTitle: {
            fontSize: tokens.fontSize.lg,
            fontWeight: tokens.fontWeight.bold,
        },
        dayContainer: {
            flex: 1,
            margin: tokens.space.xs,
            borderRadius: tokens.radius.sm,
            alignItems: 'center',
            justifyContent: 'center',
            minHeight: 60,
        },
        dayText: {
            fontSize: tokens.fontSize.sm,
            fontWeight: tokens.fontWeight.medium,
        },
        todayIndicator: {
            width: 6,
            height: 6,
            borderRadius: tokens.radius.pill,
            backgroundColor: '#007AFF',
            marginTop: tokens.space.xs,
        },
    },

    backButton: {
        paddingLeft:     tokens.space.md,
        paddingRight:    tokens.space.xl,
        flexDirection:   'row',
        justifyContent:  'center',
        alignItems:      'center',
    },

    about: {
        title: {
            fontWeight: tokens.fontWeight.bold,
            fontSize:   tokens.fontSize.xl,
            marginTop:  tokens.space.lg,
            marginLeft: tokens.space.sm,
        },
        view: {
            padding: tokens.space.md,
        },
        content: {
            marginTop:    tokens.space.sm,
            marginBottom: tokens.space.md,
        },
    },

    stackNavigator: {
        headerStyle: {
            backgroundColor: AppTheme.primary,
        },
        headerTitleStyle: {
            color:        colors.white,
            marginBottom: tokens.space.lg,
            marginTop:    tokens.space.lg,
            fontSize:     tokens.fontSize.xl,
        },
        headerBackTitleStyle: {
            color: colors.white,
        },
        headerTintColor: colors.white,
    },

    containerView: {
        margin:    tokens.space.lg,
        marginTop: tokens.space.xl,
    },

    list: {
        searchInputView: { flex: 0 },
        searchInput: {
            height:    40,
            paddingLeft: tokens.space.sm,
            color:     'white',
        },
        sectionList: { flex: 0 },

        sections: [
            { backgroundColor: 'rgba(0, 122, 255, 0.1)' },
            { backgroundColor: 'rgba(52, 199, 89, 0.1)' },
            { backgroundColor: 'rgba(255, 149, 0, 0.1)' },
            { backgroundColor: 'rgba(255, 59, 48, 0.1)' },
            { backgroundColor: 'rgba(88, 86, 214, 0.1)' },
            { backgroundColor: 'rgba(90, 200, 250, 0.1)' },
        ],
        sectionHeaders: [
            { backgroundColor: '#007AFF' },
            { backgroundColor: '#34C759' },
            { backgroundColor: '#FF9500' },
            { backgroundColor: '#FF3B30' },
            { backgroundColor: '#5856D6' },
            { backgroundColor: '#5AC8FA' },
        ],

        homeView: {
            flex:            1,
            backgroundColor: 'transparent',
        },
        view: {
            backgroundColor:  'transparent',
            borderWidth:      0,
            borderBottomColor: colors.gray,
            paddingHorizontal: tokens.space.lg,
            paddingVertical:  tokens.space.sm,
            justifyContent:   'space-between',
        },
        sectionHeaderView: {
            height:          40,
            flex:            1,
            flexDirection:   'column',
            justifyContent:  'space-around',
            alignItems:      'center',
            alignContent:    'center',
            borderBottomColor: colors.gray,
            borderRadius:    tokens.radius.sm,
            marginHorizontal: tokens.space.sm,
            marginTop:       tokens.space.sm,
            ...tokens.shadow.sm,
        },
        sectionHeaderTitle: {
            fontWeight: tokens.fontWeight.bold,
            fontSize:   tokens.fontSize.md,
        },
    },

    calendarList: {
        itemSize: 60,
    },

    Theme,
};

export { tokens, StyleWelcome };
export default style;